name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Busca o código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) (Opcional) QEMU, necessário só se você quiser multi‑arch
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 3) Configura o builder Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4) Login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5) Build & Push
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: wtmarketing/chatwoot:latest
          platforms: linux/amd64    # força só amd64
          metadata: none            # desativa manifest list/attestations
